# Generated by Django 5.0.1 on 2024-11-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_remove_area_unique_area_names_per_exercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="logentry",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "action"),
                    ("EX", "exercise"),
                    ("MA", "material"),
                    ("PE", "personnel"),
                    ("PA", "patient"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="logentry",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AR", "arrived"),
                    ("AS", "assigned"),
                    ("UA", "unassigned"),
                    ("ST", "started"),
                    ("FI", "finished"),
                    ("FR", "finished with result"),
                    ("CA", "canceled"),
                    ("IE", "in effect"),
                    ("EX", "expired"),
                    ("MO", "moved"),
                    ("TR", "triaged"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
