# Generated by Django 5.0.1 on 2024-11-14 12:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_logentry_message_logentry_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='/app/game/templmon/kdps.sig', max_length=255)),
                ('templatefile', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/app/game/templmon/log_rules/'), upload_to='log_rules/')),
            ],
        ),
    ]
