# Generated by Django 5.0.1 on 2024-11-14 12:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_logrulefile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logrulefile",
            name="signature",
            field=models.CharField(
                default="/home/claas/Desktop/BP/dps.training_k/backend/dps_training_k/game/templmon/kdps.sig",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="logrulefile",
            name="templatefile",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    location="/home/claas/Desktop/BP/dps.training_k/backend/dps_training_k/game/templmon/log_rules/"
                ),
                upload_to="log_rules/",
            ),
        ),
    ]
