# Generated by Django 5.0.1 on 2024-11-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_logrulefile_signature_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogRuleFile',
        ),
    ]
