# Generated by Django 5.0.1 on 2025-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_logentry_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logentry',
            name='unique_local_id_for_entry',
        ),
    ]
