version: '3'

services:
  # Frontend web service
  web:
    build:
      context: .
      args:
        - VITE_SERVER_URL_HTTP=${VITE_SERVER_URL_HTTP}
        - VITE_SERVER_URL_WS=${VITE_SERVER_URL_WS}
        - VITE_RUN_CONFIG=${VITE_RUN_CONFIG}
    image: dps_training_k-frontend
    container_name: K-dPS-frontend
    env_file:
      - .env.${VITE_RUN_CONFIG}
    ports:
      - "5173:5173"
    extra_hosts: # is used to ensure host.docker.internal resolves correctly on Linux systems
      - "host.docker.internal:host-gateway"
