version: '3'

services:
  # Frontend web service
  web:
    build:
      context: .
    image: dps_training_k-frontend
    container_name: K-dPS-frontend
    env_file:
      - .env.${RUN_CONFIG}
    ports:
      - "5173:5173"
