version: '3'
services:
  web:
    env_file:
      - .env.${RUN_CONFIG}
    build:
      context: .
      args:
        SERVER_URL: ${SERVER_URL}
        RUN_CONFIG: ${RUN_CONFIG}
    image: dps_training_k-frontend
    container_name: K-dPS-frontend
    ports:
      - "5173:5173"